
<!--
     File mmlaliasmap.xsl  produced by the XSL script charmap.xsl
     from input data in unicode.xml.

     Copyright 2003 - 2013 W3C.

     Use and distribution of this code are permitted under the terms of the
     W3C Software Notice and License.
     http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html

     Please report any errors to David Carlisle
     via the public W3C list www-math@w3.org.

     The numeric character values assigned to each entity
     (should) match the Unicode assignments in Unicode 5.2.
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
<xsl:character-map name="mmlalias">
  <xsl:output-character character="&#8736;" string="&amp;angle;"/>
  <xsl:output-character character="&#8289;" string="&amp;ApplyFunction;"/>
  <xsl:output-character character="&#8776;" string="&amp;approx;"/>
  <xsl:output-character character="&#8778;" string="&amp;approxeq;"/>
  <xsl:output-character character="&#8788;" string="&amp;Assign;"/>
  <xsl:output-character character="&#8780;" string="&amp;backcong;"/>
  <xsl:output-character character="&#1014;" string="&amp;backepsilon;"/>
  <xsl:output-character character="&#8245;" string="&amp;backprime;"/>
  <xsl:output-character character="&#8765;" string="&amp;backsim;"/>
  <xsl:output-character character="&#8909;" string="&amp;backsimeq;"/>
  <xsl:output-character character="&#8726;" string="&amp;Backslash;"/>
  <xsl:output-character character="&#8965;" string="&amp;barwedge;"/>
  <xsl:output-character character="&#8757;" string="&amp;because;"/>
  <xsl:output-character character="&#8757;" string="&amp;Because;"/>
  <xsl:output-character character="&#8492;" string="&amp;Bernoullis;"/>
  <xsl:output-character character="&#8812;" string="&amp;between;"/>
  <xsl:output-character character="&#8898;" string="&amp;bigcap;"/>
  <xsl:output-character character="&#9711;" string="&amp;bigcirc;"/>
  <xsl:output-character character="&#8899;" string="&amp;bigcup;"/>
  <xsl:output-character character="&#10752;" string="&amp;bigodot;"/>
  <xsl:output-character character="&#10753;" string="&amp;bigoplus;"/>
  <xsl:output-character character="&#10754;" string="&amp;bigotimes;"/>
  <xsl:output-character character="&#10758;" string="&amp;bigsqcup;"/>
  <xsl:output-character character="&#9733;" string="&amp;bigstar;"/>
  <xsl:output-character character="&#9661;" string="&amp;bigtriangledown;"/>
  <xsl:output-character character="&#9651;" string="&amp;bigtriangleup;"/>
  <xsl:output-character character="&#10756;" string="&amp;biguplus;"/>
  <xsl:output-character character="&#8897;" string="&amp;bigvee;"/>
  <xsl:output-character character="&#8896;" string="&amp;bigwedge;"/>
  <xsl:output-character character="&#10509;" string="&amp;bkarow;"/>
  <xsl:output-character character="&#10731;" string="&amp;blacklozenge;"/>
  <xsl:output-character character="&#9642;" string="&amp;blacksquare;"/>
  <xsl:output-character character="&#9652;" string="&amp;blacktriangle;"/>
  <xsl:output-character character="&#9662;" string="&amp;blacktriangledown;"/>
  <xsl:output-character character="&#9666;" string="&amp;blacktriangleleft;"/>
  <xsl:output-character character="&#9656;" string="&amp;blacktriangleright;"/>
  <xsl:output-character character="&#8869;" string="&amp;bot;"/>
  <xsl:output-character character="&#8863;" string="&amp;boxminus;"/>
  <xsl:output-character character="&#8862;" string="&amp;boxplus;"/>
  <xsl:output-character character="&#8864;" string="&amp;boxtimes;"/>
  <xsl:output-character character="&#728;" string="&amp;Breve;"/>
  <xsl:output-character character="&#8226;" string="&amp;bullet;"/>
  <xsl:output-character character="&#8783;" string="&amp;bumpeq;"/>
  <xsl:output-character character="&#8782;" string="&amp;Bumpeq;"/>
  <xsl:output-character character="&#8517;" string="&amp;CapitalDifferentialD;"/>
  <xsl:output-character character="&#8493;" string="&amp;Cayleys;"/>
  <xsl:output-character character="&#184;" string="&amp;Cedilla;"/>
  <xsl:output-character character="&#183;" string="&amp;centerdot;"/>
  <xsl:output-character character="&#183;" string="&amp;CenterDot;"/>
  <xsl:output-character character="&#10003;" string="&amp;checkmark;"/>
  <xsl:output-character character="&#8791;" string="&amp;circeq;"/>
  <xsl:output-character character="&#8634;" string="&amp;circlearrowleft;"/>
  <xsl:output-character character="&#8635;" string="&amp;circlearrowright;"/>
  <xsl:output-character character="&#8859;" string="&amp;circledast;"/>
  <xsl:output-character character="&#8858;" string="&amp;circledcirc;"/>
  <xsl:output-character character="&#8861;" string="&amp;circleddash;"/>
  <xsl:output-character character="&#8857;" string="&amp;CircleDot;"/>
  <xsl:output-character character="&#174;" string="&amp;circledR;"/>
  <xsl:output-character character="&#9416;" string="&amp;circledS;"/>
  <xsl:output-character character="&#8854;" string="&amp;CircleMinus;"/>
  <xsl:output-character character="&#8853;" string="&amp;CirclePlus;"/>
  <xsl:output-character character="&#8855;" string="&amp;CircleTimes;"/>
  <xsl:output-character character="&#8754;" string="&amp;ClockwiseContourIntegral;"/>
  <xsl:output-character character="&#8221;" string="&amp;CloseCurlyDoubleQuote;"/>
  <xsl:output-character character="&#8217;" string="&amp;CloseCurlyQuote;"/>
  <xsl:output-character character="&#9827;" string="&amp;clubsuit;"/>
  <xsl:output-character character="&#8788;" string="&amp;coloneq;"/>
  <xsl:output-character character="&#8705;" string="&amp;complement;"/>
  <xsl:output-character character="&#8450;" string="&amp;complexes;"/>
  <xsl:output-character character="&#8801;" string="&amp;Congruent;"/>
  <xsl:output-character character="&#8750;" string="&amp;ContourIntegral;"/>
  <xsl:output-character character="&#8720;" string="&amp;Coproduct;"/>
  <xsl:output-character character="&#8755;" string="&amp;CounterClockwiseContourIntegral;"/>
  <xsl:output-character character="&#8781;" string="&amp;CupCap;"/>
  <xsl:output-character character="&#8926;" string="&amp;curlyeqprec;"/>
  <xsl:output-character character="&#8927;" string="&amp;curlyeqsucc;"/>
  <xsl:output-character character="&#8910;" string="&amp;curlyvee;"/>
  <xsl:output-character character="&#8911;" string="&amp;curlywedge;"/>
  <xsl:output-character character="&#8630;" string="&amp;curvearrowleft;"/>
  <xsl:output-character character="&#8631;" string="&amp;curvearrowright;"/>
  <xsl:output-character character="&#10511;" string="&amp;dbkarow;"/>
  <xsl:output-character character="&#8225;" string="&amp;ddagger;"/>
  <xsl:output-character character="&#10871;" string="&amp;ddotseq;"/>
  <xsl:output-character character="&#8711;" string="&amp;Del;"/>
  <xsl:output-character character="&#180;" string="&amp;DiacriticalAcute;"/>
  <xsl:output-character character="&#729;" string="&amp;DiacriticalDot;"/>
  <xsl:output-character character="&#733;" string="&amp;DiacriticalDoubleAcute;"/>
  <!--U00060 DiacriticalGrave-->
  <xsl:output-character character="&#732;" string="&amp;DiacriticalTilde;"/>
  <xsl:output-character character="&#8900;" string="&amp;diamond;"/>
  <xsl:output-character character="&#8900;" string="&amp;Diamond;"/>
  <xsl:output-character character="&#9830;" string="&amp;diamondsuit;"/>
  <xsl:output-character character="&#8518;" string="&amp;DifferentialD;"/>
  <xsl:output-character character="&#989;" string="&amp;digamma;"/>
  <xsl:output-character character="&#247;" string="&amp;div;"/>
  <xsl:output-character character="&#8903;" string="&amp;divideontimes;"/>
  <xsl:output-character character="&#8784;" string="&amp;doteq;"/>
  <xsl:output-character character="&#8785;" string="&amp;doteqdot;"/>
  <xsl:output-character character="&#8784;" string="&amp;DotEqual;"/>
  <xsl:output-character character="&#8760;" string="&amp;dotminus;"/>
  <xsl:output-character character="&#8724;" string="&amp;dotplus;"/>
  <xsl:output-character character="&#8865;" string="&amp;dotsquare;"/>
  <xsl:output-character character="&#8966;" string="&amp;doublebarwedge;"/>
  <xsl:output-character character="&#8751;" string="&amp;DoubleContourIntegral;"/>
  <xsl:output-character character="&#168;" string="&amp;DoubleDot;"/>
  <xsl:output-character character="&#8659;" string="&amp;DoubleDownArrow;"/>
  <xsl:output-character character="&#8656;" string="&amp;DoubleLeftArrow;"/>
  <xsl:output-character character="&#8660;" string="&amp;DoubleLeftRightArrow;"/>
  <xsl:output-character character="&#10980;" string="&amp;DoubleLeftTee;"/>
  <xsl:output-character character="&#10232;" string="&amp;DoubleLongLeftArrow;"/>
  <xsl:output-character character="&#10234;" string="&amp;DoubleLongLeftRightArrow;"/>
  <xsl:output-character character="&#10233;" string="&amp;DoubleLongRightArrow;"/>
  <xsl:output-character character="&#8658;" string="&amp;DoubleRightArrow;"/>
  <xsl:output-character character="&#8872;" string="&amp;DoubleRightTee;"/>
  <xsl:output-character character="&#8657;" string="&amp;DoubleUpArrow;"/>
  <xsl:output-character character="&#8661;" string="&amp;DoubleUpDownArrow;"/>
  <xsl:output-character character="&#8741;" string="&amp;DoubleVerticalBar;"/>
  <xsl:output-character character="&#8595;" string="&amp;downarrow;"/>
  <xsl:output-character character="&#8659;" string="&amp;Downarrow;"/>
  <xsl:output-character character="&#8595;" string="&amp;DownArrow;"/>
  <xsl:output-character character="&#8693;" string="&amp;DownArrowUpArrow;"/>
  <xsl:output-character character="&#8650;" string="&amp;downdownarrows;"/>
  <xsl:output-character character="&#8643;" string="&amp;downharpoonleft;"/>
  <xsl:output-character character="&#8642;" string="&amp;downharpoonright;"/>
  <xsl:output-character character="&#8637;" string="&amp;DownLeftVector;"/>
  <xsl:output-character character="&#8641;" string="&amp;DownRightVector;"/>
  <xsl:output-character character="&#8868;" string="&amp;DownTee;"/>
  <xsl:output-character character="&#8615;" string="&amp;DownTeeArrow;"/>
  <xsl:output-character character="&#10512;" string="&amp;drbkarow;"/>
  <xsl:output-character character="&#8712;" string="&amp;Element;"/>
  <xsl:output-character character="&#8709;" string="&amp;emptyset;"/>
  <xsl:output-character character="&#8790;" string="&amp;eqcirc;"/>
  <xsl:output-character character="&#8789;" string="&amp;eqcolon;"/>
  <xsl:output-character character="&#8770;" string="&amp;eqsim;"/>
  <xsl:output-character character="&#10902;" string="&amp;eqslantgtr;"/>
  <xsl:output-character character="&#10901;" string="&amp;eqslantless;"/>
  <xsl:output-character character="&#8770;" string="&amp;EqualTilde;"/>
  <xsl:output-character character="&#8652;" string="&amp;Equilibrium;"/>
  <xsl:output-character character="&#8707;" string="&amp;Exists;"/>
  <xsl:output-character character="&#8496;" string="&amp;expectation;"/>
  <xsl:output-character character="&#8519;" string="&amp;exponentiale;"/>
  <xsl:output-character character="&#8519;" string="&amp;ExponentialE;"/>
  <xsl:output-character character="&#8786;" string="&amp;fallingdotseq;"/>
  <xsl:output-character character="&#8704;" string="&amp;ForAll;"/>
  <xsl:output-character character="&#8497;" string="&amp;Fouriertrf;"/>
  <xsl:output-character character="&#8805;" string="&amp;geq;"/>
  <xsl:output-character character="&#8807;" string="&amp;geqq;"/>
  <xsl:output-character character="&#10878;" string="&amp;geqslant;"/>
  <xsl:output-character character="&#8811;" string="&amp;gg;"/>
  <xsl:output-character character="&#8921;" string="&amp;ggg;"/>
  <xsl:output-character character="&#10890;" string="&amp;gnapprox;"/>
  <xsl:output-character character="&#10888;" string="&amp;gneq;"/>
  <xsl:output-character character="&#8809;" string="&amp;gneqq;"/>
  <xsl:output-character character="&#8805;" string="&amp;GreaterEqual;"/>
  <xsl:output-character character="&#8923;" string="&amp;GreaterEqualLess;"/>
  <xsl:output-character character="&#8807;" string="&amp;GreaterFullEqual;"/>
  <xsl:output-character character="&#8823;" string="&amp;GreaterLess;"/>
  <xsl:output-character character="&#10878;" string="&amp;GreaterSlantEqual;"/>
  <xsl:output-character character="&#8819;" string="&amp;GreaterTilde;"/>
  <xsl:output-character character="&#10886;" string="&amp;gtrapprox;"/>
  <xsl:output-character character="&#8919;" string="&amp;gtrdot;"/>
  <xsl:output-character character="&#8923;" string="&amp;gtreqless;"/>
  <xsl:output-character character="&#10892;" string="&amp;gtreqqless;"/>
  <xsl:output-character character="&#8823;" string="&amp;gtrless;"/>
  <xsl:output-character character="&#8819;" string="&amp;gtrsim;"/>
  <!--U02269-0FE00 gvertneqq-->
  <xsl:output-character character="&#711;" string="&amp;Hacek;"/>
  <xsl:output-character character="&#8463;" string="&amp;hbar;"/>
  <xsl:output-character character="&#9829;" string="&amp;heartsuit;"/>
  <xsl:output-character character="&#8459;" string="&amp;HilbertSpace;"/>
  <xsl:output-character character="&#10533;" string="&amp;hksearow;"/>
  <xsl:output-character character="&#10534;" string="&amp;hkswarow;"/>
  <xsl:output-character character="&#8617;" string="&amp;hookleftarrow;"/>
  <xsl:output-character character="&#8618;" string="&amp;hookrightarrow;"/>
  <xsl:output-character character="&#8463;" string="&amp;hslash;"/>
  <xsl:output-character character="&#8782;" string="&amp;HumpDownHump;"/>
  <xsl:output-character character="&#8783;" string="&amp;HumpEqual;"/>
  <xsl:output-character character="&#10764;" string="&amp;iiiint;"/>
  <xsl:output-character character="&#8749;" string="&amp;iiint;"/>
  <xsl:output-character character="&#8465;" string="&amp;Im;"/>
  <xsl:output-character character="&#8520;" string="&amp;ImaginaryI;"/>
  <xsl:output-character character="&#8464;" string="&amp;imagline;"/>
  <xsl:output-character character="&#8465;" string="&amp;imagpart;"/>
  <xsl:output-character character="&#8658;" string="&amp;Implies;"/>
  <xsl:output-character character="&#8712;" string="&amp;in;"/>
  <xsl:output-character character="&#8484;" string="&amp;integers;"/>
  <xsl:output-character character="&#8747;" string="&amp;Integral;"/>
  <xsl:output-character character="&#8890;" string="&amp;intercal;"/>
  <xsl:output-character character="&#8898;" string="&amp;Intersection;"/>
  <xsl:output-character character="&#10812;" string="&amp;intprod;"/>
  <xsl:output-character character="&#8291;" string="&amp;InvisibleComma;"/>
  <xsl:output-character character="&#8290;" string="&amp;InvisibleTimes;"/>
  <xsl:output-character character="&#10216;" string="&amp;langle;"/>
  <xsl:output-character character="&#8466;" string="&amp;Laplacetrf;"/>
  <!--U0007B lbrace-->
  <!--U0005B lbrack-->
  <xsl:output-character character="&#10216;" string="&amp;LeftAngleBracket;"/>
  <xsl:output-character character="&#8592;" string="&amp;leftarrow;"/>
  <xsl:output-character character="&#8656;" string="&amp;Leftarrow;"/>
  <xsl:output-character character="&#8592;" string="&amp;LeftArrow;"/>
  <xsl:output-character character="&#8676;" string="&amp;LeftArrowBar;"/>
  <xsl:output-character character="&#8646;" string="&amp;LeftArrowRightArrow;"/>
  <xsl:output-character character="&#8610;" string="&amp;leftarrowtail;"/>
  <xsl:output-character character="&#8968;" string="&amp;LeftCeiling;"/>
  <xsl:output-character character="&#10214;" string="&amp;LeftDoubleBracket;"/>
  <xsl:output-character character="&#8643;" string="&amp;LeftDownVector;"/>
  <xsl:output-character character="&#8970;" string="&amp;LeftFloor;"/>
  <xsl:output-character character="&#8637;" string="&amp;leftharpoondown;"/>
  <xsl:output-character character="&#8636;" string="&amp;leftharpoonup;"/>
  <xsl:output-character character="&#8647;" string="&amp;leftleftarrows;"/>
  <xsl:output-character character="&#8596;" string="&amp;leftrightarrow;"/>
  <xsl:output-character character="&#8660;" string="&amp;Leftrightarrow;"/>
  <xsl:output-character character="&#8596;" string="&amp;LeftRightArrow;"/>
  <xsl:output-character character="&#8646;" string="&amp;leftrightarrows;"/>
  <xsl:output-character character="&#8651;" string="&amp;leftrightharpoons;"/>
  <xsl:output-character character="&#8621;" string="&amp;leftrightsquigarrow;"/>
  <xsl:output-character character="&#8867;" string="&amp;LeftTee;"/>
  <xsl:output-character character="&#8612;" string="&amp;LeftTeeArrow;"/>
  <xsl:output-character character="&#8907;" string="&amp;leftthreetimes;"/>
  <xsl:output-character character="&#8882;" string="&amp;LeftTriangle;"/>
  <xsl:output-character character="&#8884;" string="&amp;LeftTriangleEqual;"/>
  <xsl:output-character character="&#8639;" string="&amp;LeftUpVector;"/>
  <xsl:output-character character="&#8636;" string="&amp;LeftVector;"/>
  <xsl:output-character character="&#8804;" string="&amp;leq;"/>
  <xsl:output-character character="&#8806;" string="&amp;leqq;"/>
  <xsl:output-character character="&#10877;" string="&amp;leqslant;"/>
  <xsl:output-character character="&#10885;" string="&amp;lessapprox;"/>
  <xsl:output-character character="&#8918;" string="&amp;lessdot;"/>
  <xsl:output-character character="&#8922;" string="&amp;lesseqgtr;"/>
  <xsl:output-character character="&#10891;" string="&amp;lesseqqgtr;"/>
  <xsl:output-character character="&#8922;" string="&amp;LessEqualGreater;"/>
  <xsl:output-character character="&#8806;" string="&amp;LessFullEqual;"/>
  <xsl:output-character character="&#8822;" string="&amp;LessGreater;"/>
  <xsl:output-character character="&#8822;" string="&amp;lessgtr;"/>
  <xsl:output-character character="&#8818;" string="&amp;lesssim;"/>
  <xsl:output-character character="&#10877;" string="&amp;LessSlantEqual;"/>
  <xsl:output-character character="&#8818;" string="&amp;LessTilde;"/>
  <xsl:output-character character="&#8810;" string="&amp;ll;"/>
  <xsl:output-character character="&#8990;" string="&amp;llcorner;"/>
  <xsl:output-character character="&#8666;" string="&amp;Lleftarrow;"/>
  <xsl:output-character character="&#9136;" string="&amp;lmoustache;"/>
  <xsl:output-character character="&#10889;" string="&amp;lnapprox;"/>
  <xsl:output-character character="&#10887;" string="&amp;lneq;"/>
  <xsl:output-character character="&#8808;" string="&amp;lneqq;"/>
  <xsl:output-character character="&#10229;" string="&amp;longleftarrow;"/>
  <xsl:output-character character="&#10232;" string="&amp;Longleftarrow;"/>
  <xsl:output-character character="&#10229;" string="&amp;LongLeftArrow;"/>
  <xsl:output-character character="&#10231;" string="&amp;longleftrightarrow;"/>
  <xsl:output-character character="&#10234;" string="&amp;Longleftrightarrow;"/>
  <xsl:output-character character="&#10231;" string="&amp;LongLeftRightArrow;"/>
  <xsl:output-character character="&#10236;" string="&amp;longmapsto;"/>
  <xsl:output-character character="&#10230;" string="&amp;longrightarrow;"/>
  <xsl:output-character character="&#10233;" string="&amp;Longrightarrow;"/>
  <xsl:output-character character="&#10230;" string="&amp;LongRightArrow;"/>
  <xsl:output-character character="&#8619;" string="&amp;looparrowleft;"/>
  <xsl:output-character character="&#8620;" string="&amp;looparrowright;"/>
  <xsl:output-character character="&#8601;" string="&amp;LowerLeftArrow;"/>
  <xsl:output-character character="&#8600;" string="&amp;LowerRightArrow;"/>
  <xsl:output-character character="&#9674;" string="&amp;lozenge;"/>
  <xsl:output-character character="&#8991;" string="&amp;lrcorner;"/>
  <xsl:output-character character="&#8624;" string="&amp;Lsh;"/>
  <!--U02268-0FE00 lvertneqq-->
  <xsl:output-character character="&#10016;" string="&amp;maltese;"/>
  <xsl:output-character character="&#8614;" string="&amp;mapsto;"/>
  <xsl:output-character character="&#8737;" string="&amp;measuredangle;"/>
  <xsl:output-character character="&#8499;" string="&amp;Mellintrf;"/>
  <xsl:output-character character="&#8723;" string="&amp;MinusPlus;"/>
  <xsl:output-character character="&#8723;" string="&amp;mp;"/>
  <xsl:output-character character="&#8888;" string="&amp;multimap;"/>
  <xsl:output-character character="&#8777;" string="&amp;napprox;"/>
  <xsl:output-character character="&#9838;" string="&amp;natural;"/>
  <xsl:output-character character="&#8469;" string="&amp;naturals;"/>
  <xsl:output-character character="&#8599;" string="&amp;nearrow;"/>
  <xsl:output-character character="&#8203;" string="&amp;NegativeMediumSpace;"/>
  <xsl:output-character character="&#8203;" string="&amp;NegativeThickSpace;"/>
  <xsl:output-character character="&#8203;" string="&amp;NegativeThinSpace;"/>
  <xsl:output-character character="&#8203;" string="&amp;NegativeVeryThinSpace;"/>
  <xsl:output-character character="&#8811;" string="&amp;NestedGreaterGreater;"/>
  <xsl:output-character character="&#8810;" string="&amp;NestedLessLess;"/>
  <xsl:output-character character="&#8708;" string="&amp;nexists;"/>
  <xsl:output-character character="&#8817;" string="&amp;ngeq;"/>
  <!--U02267-00338 ngeqq-->
  <!--U02A7E-00338 ngeqslant-->
  <xsl:output-character character="&#8815;" string="&amp;ngtr;"/>
  <xsl:output-character character="&#8602;" string="&amp;nleftarrow;"/>
  <xsl:output-character character="&#8653;" string="&amp;nLeftarrow;"/>
  <xsl:output-character character="&#8622;" string="&amp;nleftrightarrow;"/>
  <xsl:output-character character="&#8654;" string="&amp;nLeftrightarrow;"/>
  <xsl:output-character character="&#8816;" string="&amp;nleq;"/>
  <!--U02266-00338 nleqq-->
  <!--U02A7D-00338 nleqslant-->
  <xsl:output-character character="&#8814;" string="&amp;nless;"/>
  <xsl:output-character character="&#160;" string="&amp;NonBreakingSpace;"/>
  <xsl:output-character character="&#8802;" string="&amp;NotCongruent;"/>
  <xsl:output-character character="&#8742;" string="&amp;NotDoubleVerticalBar;"/>
  <xsl:output-character character="&#8713;" string="&amp;NotElement;"/>
  <xsl:output-character character="&#8800;" string="&amp;NotEqual;"/>
  <!--U02242-00338 NotEqualTilde-->
  <xsl:output-character character="&#8708;" string="&amp;NotExists;"/>
  <xsl:output-character character="&#8815;" string="&amp;NotGreater;"/>
  <xsl:output-character character="&#8817;" string="&amp;NotGreaterEqual;"/>
  <!--U02267-00338 NotGreaterFullEqual-->
  <!--U0226B-00338 NotGreaterGreater-->
  <xsl:output-character character="&#8825;" string="&amp;NotGreaterLess;"/>
  <!--U02A7E-00338 NotGreaterSlantEqual-->
  <xsl:output-character character="&#8821;" string="&amp;NotGreaterTilde;"/>
  <!--U0224E-00338 NotHumpDownHump-->
  <xsl:output-character character="&#8938;" string="&amp;NotLeftTriangle;"/>
  <xsl:output-character character="&#8940;" string="&amp;NotLeftTriangleEqual;"/>
  <xsl:output-character character="&#8814;" string="&amp;NotLess;"/>
  <xsl:output-character character="&#8816;" string="&amp;NotLessEqual;"/>
  <xsl:output-character character="&#8824;" string="&amp;NotLessGreater;"/>
  <!--U0226A-00338 NotLessLess-->
  <!--U02A7D-00338 NotLessSlantEqual-->
  <xsl:output-character character="&#8820;" string="&amp;NotLessTilde;"/>
  <xsl:output-character character="&#8832;" string="&amp;NotPrecedes;"/>
  <!--U02AAF-00338 NotPrecedesEqual-->
  <xsl:output-character character="&#8928;" string="&amp;NotPrecedesSlantEqual;"/>
  <xsl:output-character character="&#8716;" string="&amp;NotReverseElement;"/>
  <xsl:output-character character="&#8939;" string="&amp;NotRightTriangle;"/>
  <xsl:output-character character="&#8941;" string="&amp;NotRightTriangleEqual;"/>
  <xsl:output-character character="&#8930;" string="&amp;NotSquareSubsetEqual;"/>
  <xsl:output-character character="&#8931;" string="&amp;NotSquareSupersetEqual;"/>
  <!--U02282-020D2 NotSubset-->
  <xsl:output-character character="&#8840;" string="&amp;NotSubsetEqual;"/>
  <xsl:output-character character="&#8833;" string="&amp;NotSucceeds;"/>
  <!--U02AB0-00338 NotSucceedsEqual-->
  <xsl:output-character character="&#8929;" string="&amp;NotSucceedsSlantEqual;"/>
  <!--U02283-020D2 NotSuperset-->
  <xsl:output-character character="&#8841;" string="&amp;NotSupersetEqual;"/>
  <xsl:output-character character="&#8769;" string="&amp;NotTilde;"/>
  <xsl:output-character character="&#8772;" string="&amp;NotTildeEqual;"/>
  <xsl:output-character character="&#8775;" string="&amp;NotTildeFullEqual;"/>
  <xsl:output-character character="&#8777;" string="&amp;NotTildeTilde;"/>
  <xsl:output-character character="&#8740;" string="&amp;NotVerticalBar;"/>
  <xsl:output-character character="&#8742;" string="&amp;nparallel;"/>
  <xsl:output-character character="&#8832;" string="&amp;nprec;"/>
  <!--U02AAF-00338 npreceq-->
  <xsl:output-character character="&#8603;" string="&amp;nrightarrow;"/>
  <xsl:output-character character="&#8655;" string="&amp;nRightarrow;"/>
  <xsl:output-character character="&#8740;" string="&amp;nshortmid;"/>
  <xsl:output-character character="&#8742;" string="&amp;nshortparallel;"/>
  <xsl:output-character character="&#8772;" string="&amp;nsimeq;"/>
  <!--U02282-020D2 nsubset-->
  <xsl:output-character character="&#8840;" string="&amp;nsubseteq;"/>
  <!--U02AC5-00338 nsubseteqq-->
  <xsl:output-character character="&#8833;" string="&amp;nsucc;"/>
  <!--U02AB0-00338 nsucceq-->
  <!--U02283-020D2 nsupset-->
  <xsl:output-character character="&#8841;" string="&amp;nsupseteq;"/>
  <!--U02AC6-00338 nsupseteqq-->
  <xsl:output-character character="&#8938;" string="&amp;ntriangleleft;"/>
  <xsl:output-character character="&#8940;" string="&amp;ntrianglelefteq;"/>
  <xsl:output-character character="&#8939;" string="&amp;ntriangleright;"/>
  <xsl:output-character character="&#8941;" string="&amp;ntrianglerighteq;"/>
  <xsl:output-character character="&#8598;" string="&amp;nwarrow;"/>
  <xsl:output-character character="&#8750;" string="&amp;oint;"/>
  <xsl:output-character character="&#8220;" string="&amp;OpenCurlyDoubleQuote;"/>
  <xsl:output-character character="&#8216;" string="&amp;OpenCurlyQuote;"/>
  <xsl:output-character character="&#8500;" string="&amp;orderof;"/>
  <xsl:output-character character="&#8741;" string="&amp;parallel;"/>
  <xsl:output-character character="&#8706;" string="&amp;PartialD;"/>
  <xsl:output-character character="&#8916;" string="&amp;pitchfork;"/>
  <xsl:output-character character="&#177;" string="&amp;PlusMinus;"/>
  <xsl:output-character character="&#177;" string="&amp;pm;"/>
  <xsl:output-character character="&#8460;" string="&amp;Poincareplane;"/>
  <xsl:output-character character="&#8826;" string="&amp;prec;"/>
  <xsl:output-character character="&#10935;" string="&amp;precapprox;"/>
  <xsl:output-character character="&#8828;" string="&amp;preccurlyeq;"/>
  <xsl:output-character character="&#8826;" string="&amp;Precedes;"/>
  <xsl:output-character character="&#10927;" string="&amp;PrecedesEqual;"/>
  <xsl:output-character character="&#8828;" string="&amp;PrecedesSlantEqual;"/>
  <xsl:output-character character="&#8830;" string="&amp;PrecedesTilde;"/>
  <xsl:output-character character="&#10927;" string="&amp;preceq;"/>
  <xsl:output-character character="&#10937;" string="&amp;precnapprox;"/>
  <xsl:output-character character="&#10933;" string="&amp;precneqq;"/>
  <xsl:output-character character="&#8936;" string="&amp;precnsim;"/>
  <xsl:output-character character="&#8830;" string="&amp;precsim;"/>
  <xsl:output-character character="&#8473;" string="&amp;primes;"/>
  <xsl:output-character character="&#8759;" string="&amp;Proportion;"/>
  <xsl:output-character character="&#8733;" string="&amp;Proportional;"/>
  <xsl:output-character character="&#8733;" string="&amp;propto;"/>
  <xsl:output-character character="&#8461;" string="&amp;quaternions;"/>
  <xsl:output-character character="&#8799;" string="&amp;questeq;"/>
  <xsl:output-character character="&#10217;" string="&amp;rangle;"/>
  <xsl:output-character character="&#8474;" string="&amp;rationals;"/>
  <!--U0007D rbrace-->
  <!--U0005D rbrack-->
  <xsl:output-character character="&#8476;" string="&amp;Re;"/>
  <xsl:output-character character="&#8475;" string="&amp;realine;"/>
  <xsl:output-character character="&#8476;" string="&amp;realpart;"/>
  <xsl:output-character character="&#8477;" string="&amp;reals;"/>
  <xsl:output-character character="&#8715;" string="&amp;ReverseElement;"/>
  <xsl:output-character character="&#8651;" string="&amp;ReverseEquilibrium;"/>
  <xsl:output-character character="&#10607;" string="&amp;ReverseUpEquilibrium;"/>
  <xsl:output-character character="&#10217;" string="&amp;RightAngleBracket;"/>
  <xsl:output-character character="&#8594;" string="&amp;rightarrow;"/>
  <xsl:output-character character="&#8658;" string="&amp;Rightarrow;"/>
  <xsl:output-character character="&#8594;" string="&amp;RightArrow;"/>
  <xsl:output-character character="&#8677;" string="&amp;RightArrowBar;"/>
  <xsl:output-character character="&#8644;" string="&amp;RightArrowLeftArrow;"/>
  <xsl:output-character character="&#8611;" string="&amp;rightarrowtail;"/>
  <xsl:output-character character="&#8969;" string="&amp;RightCeiling;"/>
  <xsl:output-character character="&#10215;" string="&amp;RightDoubleBracket;"/>
  <xsl:output-character character="&#8642;" string="&amp;RightDownVector;"/>
  <xsl:output-character character="&#8971;" string="&amp;RightFloor;"/>
  <xsl:output-character character="&#8641;" string="&amp;rightharpoondown;"/>
  <xsl:output-character character="&#8640;" string="&amp;rightharpoonup;"/>
  <xsl:output-character character="&#8644;" string="&amp;rightleftarrows;"/>
  <xsl:output-character character="&#8652;" string="&amp;rightleftharpoons;"/>
  <xsl:output-character character="&#8649;" string="&amp;rightrightarrows;"/>
  <xsl:output-character character="&#8605;" string="&amp;rightsquigarrow;"/>
  <xsl:output-character character="&#8866;" string="&amp;RightTee;"/>
  <xsl:output-character character="&#8614;" string="&amp;RightTeeArrow;"/>
  <xsl:output-character character="&#8908;" string="&amp;rightthreetimes;"/>
  <xsl:output-character character="&#8883;" string="&amp;RightTriangle;"/>
  <xsl:output-character character="&#8885;" string="&amp;RightTriangleEqual;"/>
  <xsl:output-character character="&#8638;" string="&amp;RightUpVector;"/>
  <xsl:output-character character="&#8640;" string="&amp;RightVector;"/>
  <xsl:output-character character="&#8787;" string="&amp;risingdotseq;"/>
  <xsl:output-character character="&#9137;" string="&amp;rmoustache;"/>
  <xsl:output-character character="&#8667;" string="&amp;Rrightarrow;"/>
  <xsl:output-character character="&#8625;" string="&amp;Rsh;"/>
  <xsl:output-character character="&#8600;" string="&amp;searrow;"/>
  <xsl:output-character character="&#8726;" string="&amp;setminus;"/>
  <xsl:output-character character="&#8595;" string="&amp;ShortDownArrow;"/>
  <xsl:output-character character="&#8592;" string="&amp;ShortLeftArrow;"/>
  <xsl:output-character character="&#8739;" string="&amp;shortmid;"/>
  <xsl:output-character character="&#8741;" string="&amp;shortparallel;"/>
  <xsl:output-character character="&#8594;" string="&amp;ShortRightArrow;"/>
  <xsl:output-character character="&#8593;" string="&amp;ShortUpArrow;"/>
  <xsl:output-character character="&#8771;" string="&amp;simeq;"/>
  <xsl:output-character character="&#8728;" string="&amp;SmallCircle;"/>
  <xsl:output-character character="&#8726;" string="&amp;smallsetminus;"/>
  <xsl:output-character character="&#9824;" string="&amp;spadesuit;"/>
  <xsl:output-character character="&#8730;" string="&amp;Sqrt;"/>
  <xsl:output-character character="&#8847;" string="&amp;sqsubset;"/>
  <xsl:output-character character="&#8849;" string="&amp;sqsubseteq;"/>
  <xsl:output-character character="&#8848;" string="&amp;sqsupset;"/>
  <xsl:output-character character="&#8850;" string="&amp;sqsupseteq;"/>
  <xsl:output-character character="&#9633;" string="&amp;Square;"/>
  <xsl:output-character character="&#8851;" string="&amp;SquareIntersection;"/>
  <xsl:output-character character="&#8847;" string="&amp;SquareSubset;"/>
  <xsl:output-character character="&#8849;" string="&amp;SquareSubsetEqual;"/>
  <xsl:output-character character="&#8848;" string="&amp;SquareSuperset;"/>
  <xsl:output-character character="&#8850;" string="&amp;SquareSupersetEqual;"/>
  <xsl:output-character character="&#8852;" string="&amp;SquareUnion;"/>
  <xsl:output-character character="&#8902;" string="&amp;Star;"/>
  <xsl:output-character character="&#1013;" string="&amp;straightepsilon;"/>
  <xsl:output-character character="&#981;" string="&amp;straightphi;"/>
  <xsl:output-character character="&#8834;" string="&amp;subset;"/>
  <xsl:output-character character="&#8912;" string="&amp;Subset;"/>
  <xsl:output-character character="&#8838;" string="&amp;subseteq;"/>
  <xsl:output-character character="&#10949;" string="&amp;subseteqq;"/>
  <xsl:output-character character="&#8838;" string="&amp;SubsetEqual;"/>
  <xsl:output-character character="&#8842;" string="&amp;subsetneq;"/>
  <xsl:output-character character="&#10955;" string="&amp;subsetneqq;"/>
  <xsl:output-character character="&#8827;" string="&amp;succ;"/>
  <xsl:output-character character="&#10936;" string="&amp;succapprox;"/>
  <xsl:output-character character="&#8829;" string="&amp;succcurlyeq;"/>
  <xsl:output-character character="&#8827;" string="&amp;Succeeds;"/>
  <xsl:output-character character="&#10928;" string="&amp;SucceedsEqual;"/>
  <xsl:output-character character="&#8829;" string="&amp;SucceedsSlantEqual;"/>
  <xsl:output-character character="&#8831;" string="&amp;SucceedsTilde;"/>
  <xsl:output-character character="&#10928;" string="&amp;succeq;"/>
  <xsl:output-character character="&#10938;" string="&amp;succnapprox;"/>
  <xsl:output-character character="&#10934;" string="&amp;succneqq;"/>
  <xsl:output-character character="&#8937;" string="&amp;succnsim;"/>
  <xsl:output-character character="&#8831;" string="&amp;succsim;"/>
  <xsl:output-character character="&#8715;" string="&amp;SuchThat;"/>
  <xsl:output-character character="&#8721;" string="&amp;Sum;"/>
  <xsl:output-character character="&#8835;" string="&amp;Superset;"/>
  <xsl:output-character character="&#8839;" string="&amp;SupersetEqual;"/>
  <xsl:output-character character="&#8835;" string="&amp;supset;"/>
  <xsl:output-character character="&#8913;" string="&amp;Supset;"/>
  <xsl:output-character character="&#8839;" string="&amp;supseteq;"/>
  <xsl:output-character character="&#10950;" string="&amp;supseteqq;"/>
  <xsl:output-character character="&#8843;" string="&amp;supsetneq;"/>
  <xsl:output-character character="&#10956;" string="&amp;supsetneqq;"/>
  <xsl:output-character character="&#8601;" string="&amp;swarrow;"/>
  <xsl:output-character character="&#8756;" string="&amp;therefore;"/>
  <xsl:output-character character="&#8756;" string="&amp;Therefore;"/>
  <xsl:output-character character="&#8776;" string="&amp;thickapprox;"/>
  <xsl:output-character character="&#8764;" string="&amp;thicksim;"/>
  <xsl:output-character character="&#8201;" string="&amp;ThinSpace;"/>
  <xsl:output-character character="&#8764;" string="&amp;Tilde;"/>
  <xsl:output-character character="&#8771;" string="&amp;TildeEqual;"/>
  <xsl:output-character character="&#8773;" string="&amp;TildeFullEqual;"/>
  <xsl:output-character character="&#8776;" string="&amp;TildeTilde;"/>
  <xsl:output-character character="&#10536;" string="&amp;toea;"/>
  <xsl:output-character character="&#10537;" string="&amp;tosa;"/>
  <xsl:output-character character="&#9653;" string="&amp;triangle;"/>
  <xsl:output-character character="&#9663;" string="&amp;triangledown;"/>
  <xsl:output-character character="&#9667;" string="&amp;triangleleft;"/>
  <xsl:output-character character="&#8884;" string="&amp;trianglelefteq;"/>
  <xsl:output-character character="&#8796;" string="&amp;triangleq;"/>
  <xsl:output-character character="&#9657;" string="&amp;triangleright;"/>
  <xsl:output-character character="&#8885;" string="&amp;trianglerighteq;"/>
  <xsl:output-character character="&#8411;" string="&amp;TripleDot;"/>
  <xsl:output-character character="&#8606;" string="&amp;twoheadleftarrow;"/>
  <xsl:output-character character="&#8608;" string="&amp;twoheadrightarrow;"/>
  <xsl:output-character character="&#8988;" string="&amp;ulcorner;"/>
  <xsl:output-character character="&#8899;" string="&amp;Union;"/>
  <xsl:output-character character="&#8846;" string="&amp;UnionPlus;"/>
  <xsl:output-character character="&#8593;" string="&amp;uparrow;"/>
  <xsl:output-character character="&#8657;" string="&amp;Uparrow;"/>
  <xsl:output-character character="&#8593;" string="&amp;UpArrow;"/>
  <xsl:output-character character="&#8645;" string="&amp;UpArrowDownArrow;"/>
  <xsl:output-character character="&#8597;" string="&amp;updownarrow;"/>
  <xsl:output-character character="&#8661;" string="&amp;Updownarrow;"/>
  <xsl:output-character character="&#8597;" string="&amp;UpDownArrow;"/>
  <xsl:output-character character="&#10606;" string="&amp;UpEquilibrium;"/>
  <xsl:output-character character="&#8639;" string="&amp;upharpoonleft;"/>
  <xsl:output-character character="&#8638;" string="&amp;upharpoonright;"/>
  <xsl:output-character character="&#8598;" string="&amp;UpperLeftArrow;"/>
  <xsl:output-character character="&#8599;" string="&amp;UpperRightArrow;"/>
  <xsl:output-character character="&#965;" string="&amp;upsilon;"/>
  <xsl:output-character character="&#8869;" string="&amp;UpTee;"/>
  <xsl:output-character character="&#8613;" string="&amp;UpTeeArrow;"/>
  <xsl:output-character character="&#8648;" string="&amp;upuparrows;"/>
  <xsl:output-character character="&#8989;" string="&amp;urcorner;"/>
  <xsl:output-character character="&#1013;" string="&amp;varepsilon;"/>
  <xsl:output-character character="&#1008;" string="&amp;varkappa;"/>
  <xsl:output-character character="&#8709;" string="&amp;varnothing;"/>
  <xsl:output-character character="&#981;" string="&amp;varphi;"/>
  <xsl:output-character character="&#982;" string="&amp;varpi;"/>
  <xsl:output-character character="&#8733;" string="&amp;varpropto;"/>
  <xsl:output-character character="&#1009;" string="&amp;varrho;"/>
  <xsl:output-character character="&#962;" string="&amp;varsigma;"/>
  <!--U0228A-0FE00 varsubsetneq-->
  <!--U02ACB-0FE00 varsubsetneqq-->
  <!--U0228B-0FE00 varsupsetneq-->
  <!--U02ACC-0FE00 varsupsetneqq-->
  <xsl:output-character character="&#977;" string="&amp;vartheta;"/>
  <xsl:output-character character="&#8882;" string="&amp;vartriangleleft;"/>
  <xsl:output-character character="&#8883;" string="&amp;vartriangleright;"/>
  <xsl:output-character character="&#8744;" string="&amp;vee;"/>
  <xsl:output-character character="&#8897;" string="&amp;Vee;"/>
  <!--U0007C vert-->
  <xsl:output-character character="&#8214;" string="&amp;Vert;"/>
  <xsl:output-character character="&#8739;" string="&amp;VerticalBar;"/>
  <xsl:output-character character="&#8768;" string="&amp;VerticalTilde;"/>
  <xsl:output-character character="&#8202;" string="&amp;VeryThinSpace;"/>
  <xsl:output-character character="&#8743;" string="&amp;wedge;"/>
  <xsl:output-character character="&#8896;" string="&amp;Wedge;"/>
  <xsl:output-character character="&#8472;" string="&amp;wp;"/>
  <xsl:output-character character="&#8768;" string="&amp;wr;"/>
  <xsl:output-character character="&#8488;" string="&amp;zeetrf;"/>
</xsl:character-map>

</xsl:stylesheet>
